In [1]:
import sys

print("Python executable:", sys.executable)
print("Python version:", sys.version)

Python executable: d:\Soft\Python312\python.exe
Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

In [2]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

Current working directory:
d:\Coding\NTUHomeworks\AssignmentOfCA6000\notebooks

检查已经具有哪些包

In [3]:
import sys

print("Python:", sys.version)

packages = [
    "pandas",
    "numpy",
    "matplotlib",
    "sklearn"
]

for package in packages:
    try:
        module = __import__(package)
        version = getattr(module, "__version__", "unknown")
        print(f"{package}: {version}")
    except ImportError:
        print(f"{package}: NOT INSTALLED")

Python: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
pandas: 3.0.3
numpy: 2.5.1
matplotlib: 3.11.1
sklearn: 1.9.0

In [1]:
from pathlib import Path

# 当前 Notebook 工作目录
notebook_dir = Path.cwd()

# 项目根目录：notebooks 的上一级
project_root = notebook_dir.parent

print("Notebook working directory:")
print(notebook_dir)

print("\nProject root:")
print(project_root)

print("\nProject root exists:")
print(project_root.exists())

Notebook working directory:
d:\Coding\NTUHomeworks\AssignmentOfCA6000\notebooks

Project root:
d:\Coding\NTUHomeworks\AssignmentOfCA6000

Project root exists:
True

确认是否可以按照路径访问到数据集

In [2]:
csv_files = list(project_root.rglob("*.csv"))

print(f"Found {len(csv_files)} CSV file(s):\n")

for file in csv_files:
    print(file.relative_to(project_root))

Found 4 CSV file(s):

data\raw\sample_submission.csv
data\raw\store.csv
data\raw\test.csv
data\raw\train.csv

In [ ]:
import pandas as pd

train_files = list(project_root.rglob("train.csv"))
store_files = list(project_root.rglob("store.csv"))

print("train.csv:", train_files)
print("store.csv:", store_files)

train.csv: [WindowsPath('d:/Coding/NTUHomeworks/AssignmentOfCA6000/data/raw/train.csv')]
store.csv: [WindowsPath('d:/Coding/NTUHomeworks/AssignmentOfCA6000/data/raw/store.csv')]

确认是否可以正确访问数据集中指定数据

In [4]:
train_path = train_files[0]
store_path = store_files[0]

train_test = pd.read_csv(train_path, nrows=5)
store_test = pd.read_csv(store_path, nrows=5)

print("train.csv loaded successfully")
display(train_test)

print("store.csv loaded successfully")
display(store_test)

train.csv loaded successfully

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

store.csv loaded successfully

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270,9,2008,0,NaN,NaN,NaN
1,2,a,a,570,11,2007,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130,12,2006,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620,9,2009,0,NaN,NaN,NaN
4,5,a,a,29910,4,2015,0,NaN,NaN,NaN